### ISSUE TITLE
How to use this cursor in Xcode 7.3beta

### ISSUE THREAD

**Issue by HiJackXD** [jorge/xcode-cursor-fix#1]
I've replaced the file, but didnt works.
:<

**Comment by jorge** [comment]
Fixed path to cursor in caba4e7. If you're using an Xcode beta though, you'll need to change the application you're copying the cursor to. 

You'd need to change the cp in `cp DVTIbeamCursor@2x.tiff /Applications/Xcode.app...`

to

`cp DVTIbeamCursor@2x.tiff /Applications/Xcode\ Beta.app...` or whatever the actual file name for the beta Xcode is. Hope that helps!

**Comment by HiJackXD** [comment]
Thx!But didnt work either.
